nuclio/deploy.py
Required as a result of project display name deprecation in nuclio 
https://github.com/nuclio/nuclio/pull/1314
`displayName` is still passed in the request, to support older versions of nuclio
=> [Fix] Update nuclio project creation request

nuclio/archive.py, nuclio/config.py, nuclio/deploy.py, tests/test_build.py, tests/test_deploy.py
Project `spec.displayName` field is deprecated, and soon would be blocked [see here](https://github.com/nuclio/nuclio/pull/1971)
+ few fixes
=> Do not create project with displayName

.gitignore, nuclio/export.py, tests/test_export.py
Fix ignored magic commands outside of defined code blocks with `start-code` or `end-code` notations.
Now every magic command in the notebook should apply on all functions in that notebook.
Cells with magic commands will be applied once seen and code will be added to the function accordingly to the start\end code notations.
=> Fix magic commands not being handled outside of start/end block

tests/test_build.py
Added pytest fixtures to yield url_filename/project name and remove `test_build` outputs upon test completion (teardown).
=> Add pytest fixtures to handle deletion of tests outputs

Pipfile, nuclio/utils.py
Migrate to jupyter_server - fix listing servers from both jupyter notebook and jupyter server with `nbserver` and `jpserver` respectively.
Our hacky code to resolve the running notebook name failed in the mlrun-kit jupyter, the reason was we used the new jupyter server introduced here: https://github.com/jupyter-server/jupyter_server .
the new server's metadata json is named `jpserver-{id}.json` while the old server's metadata is `nbserver-{id}.json`.
Hence, while listing the servers we couldn't find the correct server (and therefore the session) of the current notebook.
The solution was to chain the generators listing both types of servers and supporting both servers.
=> Fix running notebook name resolution when it is a Jupyter server

Pipfile, nuclio/utils.py, setup.py
`jupyter-server` was added in https://github.com/nuclio/nuclio-jupyter/pull/110 to fix the current notebook name resolution logic to work in new Jupyter.
Installing it on the Iguazio Jupyter (which is the old notebook-server one) caused to un-wanted-ly upgrading tornado which causes problems, as a solution we tried (https://github.com/nuclio/nuclio-jupyter/pull/113) to limit jupyter-server to a version (<=1.0.8) that its tornado requirement is compatible with the Iguazio Jupyter's tornado version 
But this caused a crash in the mlrun-kit Jupyter which is running a much newer jupyter-server (1.6.4)
So the current suggested solution (done in this PR) is to remove jupyter-server from this package requirements, and adding it as an extra or the package, that way only if explicitly requested …
=> Move jupyter-server requirement to be a package extra 

nuclio/export.py, tests/code_generation_test_cases.yml, tests/test_export.py
code_to_function fails with MagicError if notebook has a commented out magic, we now filter comments from code before parsing cell and line magic.
Bug happened during running mlrun demo realtime-face-recognition.
=> Fix commented out magic parsing

nuclio/build.py, nuclio/deploy.py, tests/test_export.py, tests/test_install.py
`tempfile.mktemp()` manifests a known vulnerability wrt race condition between setting the path and obtaining the file handle, which is sometimes worrying, and pops up in security scans even when used in a safe context - https://cwe.mitre.org/data/definitions/377
It is hence deemed deprecated and vulnerable: https://docs.python.org/3/library/tempfile.html#deprecated-functions-and-variables
The underlying issue here will still exist in some cases because the use case is valid - however, we will appease the scans
=> Scrubbing mktemp calls (CVE)

nuclio/config.py, nuclio/utils.py, tests/test_config.py, tests/test_deploy.py
Enable adding to nuclio function spec env variables that originate from a k8s secret and key, e.g. `{"name": "ENV1", "valueFrom": {"secretKeyRef": {"name": "secret1", "key": "secret-key1"}}}`.
We will receive a dict of external source env i.e. `name` to `valueFrom` mapping, and add it to the config on `merge`.
=> Set env variables from k8s secrets in config spec

nuclio/export.py, tests/code_generation_test_cases.yml
Instead of filtering all comments when extracting code from the notebook, only filter magic and code annotations.
=> Keep comments on code extraction between start\end code annotations

.github/workflows/CI.yaml, README.md, docs/index.rst, docs/nlp-example.ipynb, docs/nuclio-example.ipynb, nuclio/config.py, tests/deploy.json
Instead of explicitly use python:3.6 version, default to `python` which is determined by nuclio's BE
=> Change nuclio default runtime version

Pipfile
https://github.com/jupyter/nbconvert/issues/1736
jinja2 3.1.0 deprecated jinja2.utils.escape which is being used by nbconvert.
pinning jinja2 version to ~=3.0.0 fixes the issue for now.
Added todo to remove the requirement once jupyter/nbconvert which are using the package resolve the issue
=> [Requirements] Pin jinja2 version to ~=3.0.0 and add upper bound to pyyaml <6.0.0

nuclio/triggers.py
Add documentation. Sourced from:
• [project_runner example](https://github.com/mlrun/functions/blob/development/project_runner/project_runner.ipynb)
• Nuclio UI (Iguazio Project > Realtime functions > Nuclio UI > Triggers tab)
=> Document Nuclio CronTrigger / MLRun add_trigger()

Pipfile
As https://github.com/jupyter/nbconvert/issues/1736 was resolved and the fix https://github.com/jupyter/nbconvert/pull/1737 is available from nbconvert release 6.4.5.
=> [Requirements] Unpin jinja2 and bump nbconvert to 6.4.5

nuclio/config.py, tests/test_config.py
fix for update_env_var:
- rename `update_env_var` to `create_or_update_env_var`
- Improve logic readability
- add setdefault for config.spec["env"] to avoid KeyError
=> Config - safely load env from config.spec

nuclio/triggers.py, tests/test_triggers.py
Support enabling explicit ack in Kafka and V3IO stream triggers.
The supported modes are:
- "disable"
- "enable"
- "explicitOnly"
When not given, the Nuclio backend defaults the mode to "disable".
=> Stream Trigger - support explicit ack mode

nuclio/request.py
When multiple loggers are created with the same name, remove duplicate handlers so they won't logs the same messages multiple times.
Porting the fix from https://github.com/mlrun/mlrun/pull/3381 to nuclio-jupyter.
=> [Logger] Fix multiple logs for multiple handlers

nuclio/triggers.py
We hardcoded maxWorkers parameter for kafka trigger, so it was always equal to 1. In this PR we make this parameter configurable.
https://jira.iguazeng.com/browse/NUC-120
=> [Kafka] Make max_workers a configurable parameter for kafka trigger

nuclio/triggers.py, tests/test_triggers.py
Jira - https://jira.iguazeng.com/browse/NUC-128
=> Fix unconventional naming of V3IOStreamTrigger parameters by deprecating them

nuclio/build.py, nuclio/utils.py
Jira - https://iguazio.atlassian.net/browse/ML-2223
This PR addresses the issue of IPython Notebook (.ipynb) names containing dots.
=> Delete dots from the file name

nuclio/build.py
This PR addresses the issue where the name of a file in Nuclio conflicts with an existing Python library, causing the import to fail. To avoid such issues, we will add a `nuclio` suffix to the filename when a function is being created from a file. 
Jira - https://iguazio.atlassian.net/browse/ML-6737
=> [Build] Add a `nuclio` suffix to the module name if function is being deployed from the file

Pipfile
It conflicts with the requirements in MLRun https://github.com/mlrun/mlrun/blob/development/extras-requirements.txt#L16
=> [Requirements] Limit boto3 version

Pipfile, Pipfile.lock, nuclio/utils.py, setup.py
Notebook servers are no longer used by MLRun CE and Iguazio and the old jupyter server has security vulnerabilities.
Note this change requires bumping minor version when releasing so that mlrun < 1.8 will not pick this up.
https://iguazio.atlassian.net/browse/ML-8218
=> [Utils] Remove legacy notebook server and bump jupyter server

Pipfile, Pipfile.lock
Bumping to 6.0 causes discrepancies with iguazio jupyters
https://iguazio.atlassian.net/browse/ML-8302
=> [Requirements] Loosen ipykernel version requirement to support 5.x

nuclio/archive.py, nuclio/build.py, tests/test_build.py
Previously, when `build_file` was called with an S3 path, the content fetched via `S3Repo.get()` was returned as bytes. This caused issues later in the `code2config` flow, where a string was expected and operations like `encode` failed.
This PR fixes the bug by updating `S3Repo.get()` to decode the S3 object content into a string.
Jira:
https://iguazio.atlassian.net/browse/ML-10411
=> [Archive] Fix S3Repo to return decoded string instead of bytes
